import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

url = "https://raw.githubusercontent.com/ageron/handson-ml2/refs/heads/master/datasets/housing/housing.csv"
housing = pd.read_csv(url)
print("Shape is; ", housing.shape)
print(housing.head(5))
print(housing.columns.to_list())
print(housing.dtypes)
print(housing.info())
print(housing.describe())
print(housing.columns.to_list())
print(housing["median_income"].min())
print(housing["median_income"].max())
print(housing["median_income"].mean())
print(housing["total_bedrooms"].value_counts())
print(housing["total_bedrooms"].nunique())
print(housing["median_income"].nunique())
print(housing["median_income"].std())
print(housing.isnull().sum())
print(housing.isnull().sum().sum())
print(housing.isnull().sum() / len(housing) * 100)
print(housing["total_bedrooms"].isna())
print(housing[housing["total_bedrooms"].isna()])
print(housing["ocean_proximity"])
print(housing[["ocean_proximity"]])
print(housing[["median_income" ,"ocean_proximity"]])
print(housing.columns.to_list())
print(housing.latitude)
print(housing.median_income)
print(housing.iloc[0])
print(housing.iloc[-1])
print(housing.iloc[0:5])
print(housing.iloc[[0,2,4]])
print(housing.iloc[0:5, 0:3])
print(housing.iloc[:, -1])
print(housing.loc[1])
print((housing["housing_median_age"] > 30).sum())
print(housing[housing["ocean_proximity"] == "NEAR BAY"])
print(housing[housing["ocean_proximity"] != "NEAR BAY"])
print(housing[(housing["housing_median_age"] > 30) & (housing["ocean_proximity"] == "INLAND")])
print(housing[housing["ocean_proximity"].isin(["NEAR BAY", "INLAND"])])
print(housing[housing["ocean_proximity"].isin(["NEAR BAY"])])
print(housing[~housing["ocean_proximity"].isin(["NEAR BAY", "INLAND"])])
print("20 to 30 years old houses: ", housing[housing["housing_median_age"].between(20, 30)])

housing["new_column"] = 0
print(housing.head(5))
print(housing.columns.to_list())
housing["all_rooms"] = housing["total_bedrooms"] + housing["total_rooms"]
print(housing.head(5))
housing['house_value_per_household'] = housing["median_house_value"] / housing["households"]
print(housing.head())
housing["double_med_income"] = housing["median_income"].apply(lambda x: x * 2)
print(housing.head())
housing["age_category"] = np.where(housing["housing_median_age"] > 30, "old", "young")
print(housing.head())
